server:
  port: 8001
  servlet:
    context-path: /godeye
logging:
  config: classpath:logback.xml
spring:
  redis:
    cluster:
     max-redirects: 8
     nodes: 192.168.1.102:7001,192.168.1.102:7002,192.168.1.102:7003,192.168.1.102:7004,192.168.1.102:7005,192.168.1.102:7006
    host: 10.45.47.48
    port: 6379
    database: 1
    timeout: 2000
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://gstvip:3306/gstdb?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    #    username: gstadmin
    #    password: gstadmin
    url: jdbc:mysql://119.23.128.223:3306/iotdb?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: iotadmin
    password: iotadmin
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 50
    maxWait: 10000
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    validationQuery: select 1 from dual
    timeBetweenEvictionRunsMillis: 30000
    numTestsPerEvictionRun: 32
    minEvictableIdleTimeMillis: 1800000
    removeAbandoned: true
    removeAbandonedTimeout: 180


